import {
  ElButton,
  ElInput,
  ElSwitch,
  ElRate,
  ElRadioGroup,
  ElRadio,
  ElRadioButton,
  ElSelect,
  ElInputNumber,
  ElInputTag,
  ElSlider,
  ElColorPicker,
  ElOption,
  ElSelectV2,
  ElDatePicker,
  ElFormItem,
  ElTimePicker,
  ElSegmented,
  ElCheckboxGroup,
  ElCheckbox,
} from 'element-plus'


export const componentsMap: any = {
  input: ElInput,
  textarea: ElInput,
  inputNumber: ElInputNumber,
  inputTag: ElInputTag,
  rate: ElRate,
  radioGroup: ElRadioGroup,
  radio: ElRadio,
  radioButton: ElRadioButton,
  select: ElSelect,
  switch: ElSwitch,
  slider: ElSlider,
  colorPicker: ElColorPicker,
  div: 'div',
  option: ElOption,
  selectV2: ElSelectV2,
  datePicker: ElDatePicker,
  timePicker: ElTimePicker,
  formItem: ElFormItem,
  segmented: ElSegmented,
  checkboxGroup: ElCheckboxGroup,
  checkbox: ElCheckbox,
}

export type TComponentName = keyof typeof componentsMap
